name: dbt_airbnb

profile: airbnb

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
  - "target-prod"

#seeds:
  # Builds seeds into '<your_schema_name>_raw'
  #dbt_airbnb:
    #+schema: raw

on-run-start: #Hooks to run at the start of a dbt run
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log (
      model_name STRING,
      run_timestamp TIMESTAMP
    )"

models:
  dbt_airbnb:
    +grants: 
      select: ["transform"] #Grant select permissions to transform on all models in the dbt_airbnb project
    +post-hook: #Post hooks to run after a model is built
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"
    +materialized: view

    src:
      +materialized: ephemeral

    dim:
      +materialized: view

    fct:
      +materialized: table
      +tags: ['fact']

    mart:
      +materialized: table
      +tags: ['fact']

data_tests:
  #+store_failures: true
  +schema: _tests_failures #store failed records in a the schema, use the SQL query generated to review the errors

vars:
  user_name: "Mariana"