name: dbt_airbnb

profile: airbnb

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

#seeds:
  # Builds seeds into '<your_schema_name>_raw'
  #dbt_airbnb:
    #+schema: raw

models:
  dbt_airbnb:
    +materialized: view

    src:
      +materialized: ephemeral

    dim:
      +materialized: view

    fct:
      +materialized: table